# -*- coding: utf-8 -*-
"""skeras.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_rjGS62YPqUv270C7hXl49vgOS_EeeYT
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import matplotlib

def save_history_history(fname,history_history,fold=''):
  np.save(os.path.join(fold,fname), history_history)

def load_history_history(fname,fold=''):
  history_history = np.load(os.path.join(fold,fname)).item(0)
  return history_history

def plot_acc(history, title=None, show_flag = False):
  if not isinstance(history, dict):
    history = history.history
  plt.plot(history['accuracy'],label = 'Training')
  plt.plot(history['val_accuracy'], label = 'Validtion')
  if title is not None:
    plt.title(title)
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend()
  if show_flag:
    plt.show()

def plot_loss(history, title=None, show_flag = False):
  if not isinstance(history, dict):
    history = history.history
  plt.plot(history['loss'],label = 'Training')
  plt.plot(history['val_loss'], label = 'Validtion')
  if title is not None:
    plt.title(title)
  plt.xlabel('Epoch')
  plt.ylabel('Loss')
  plt.legend()
  if show_flag:
    plt.show()

def plot_history(history):
  plt.figure(figsize=(15,5))
  plt.subplot(1,2,1)
  plot_acc(history)
  plt.subplot(1,2,2)
  plot_loss(history)

